# Usar Node.js como base
FROM node:18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del frontend al contenedor
COPY . .

# Instalar dependencias
RUN npm install

# Construir la aplicación en modo producción
RUN npm run build

# Instalar un servidor web para servir el frontend (Nginx)
RUN npm install -g serve

# Exponer el puerto 3000
EXPOSE 3000

# Comando para iniciar el frontend
CMD ["serve", "-s", "build", "-l", "3000"]
