version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: GestionClientes
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Montamos el archivo init.sql

  backend:
    build: .
    container_name: backend_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: GestionClientes

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
